spring:
  liquibase:
    change-log: classpath:/db.changelog/changelog-master.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/marketplace
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        #drop and create new tables
        ddl-auto: create
        temp: use_jdbc_metadata_defaults = false
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false

server:
  port: 8080

logging:
  file:
    name: logging-data.log
  logback:
    rollingpolicy:
      file-name-pattern: Liquibase-Demo-%d{yyyy-MM-dd}.%i.log
      max-file-size: 1MB
      total-size-cap: 10MB
      max-history: 14
  level:
    org.springframework.web: info